### ISSUE TITLE
Github action plan

### ISSUE THREAD

**Issue by a4z** [cross-language-cpp/djinni-support-lib#4]
How to continuously build and test the support lib ?

Use github action, but to do what exactly

**Comment by jothepro** [comment]
I wonder if it makes sense integrate [this test-suite](https://github.com/cross-language-cpp/djinni/tree/master/test-suite) integration-tests into `djinni-support-lib`?

**Comment by a4z** [comment]
Parts of it for sure, but the test are pretty dated, and at least on the Mac platforms some things changed, for example, fat binaries are not a thing anymore, so the build for osx script needs to be reworked.

But, basically I think it could work like:
Having some generated files, using them together with the support lib to have a java / objectivC program to compile and run and verify that everything works. (compiles and runs)
So I plan to start very super simple :-)

**Comment by a4z** [comment]
Since we have some gh actions in the project now, this is done.
Adding improvements to those actions could be an other topic/issue
