### ISSUE TITLE
Conan recipe and java files

### ISSUE THREAD

**Issue by paulo-coutinho** [cross-language-cpp/djinni-support-lib#59]
Hi,

When i build my java library in my project ezored (github.com/ezored/ezored) i copy java files folder from support-lib to my library (support-lib/java).

But when i migrate to conan recipe, how i can copy the java folder to my library folder? How can i access the support-lib recipe files to copy java folder?

Thanks.

**Comment by jothepro** [comment]
We currently don't package the NativeLibLoader into the conan recipe. In https://github.com/cross-language-cpp/djinni-support-lib/issues/8 we decided that we only want to use it internally for testing purposes but don't plan to publish it. So unfortunately you'll still have to copy the sourcefile to your project manually, if you want to use it. :/

If you really wanted to include it as a dependency, I guess the cleanest solution would be to publish it as a maven artifact? I have no plans to do so, but feel free to contribute this or another solution. 🤔

**Comment by paulo-coutinho** [comment]
Hi, thanks.

I still copy support-lib files to my project to have this.
