### ISSUE TITLE
Support for weak pointers

### ISSUE THREAD

**Issue by eakoli** [cross-language-cpp/djinni-support-lib#65]
The current design of the proxies that are passed to c++ is that they hold a strong reference to the proxied object, and the proxy factory holds a weak reference to the proxy. This results in a situation where if the C++ side wants to hold a std::weak_ptr to the proxy, it cannot, as the proxy is automatically destroyed once all users of the proxy discard it.

This creates issues when using a delegate pattern where the platform object creates a c++ object and passes it a delegate interface. The C++ code has to maintain a strong reference (or the proxy is destroyed) and the delegate implementation has to hold a weak reference to the platform object. This can easily become cumbersome (especially on java where you cannot just decorate a member as weak). Additionally it requires de-registration of the delegate in some circumstances to properly clean up and not leave "dangling" objects.

I'm primarily looking for feedback on if this could be included in the core code, which options would be more likely to be accepted, etc.

To implement this it requires a "weak_ptr" conforming template (we cannot use weak_ptr directly because it cannot be partially specialized, and full specialization proved to be problematic)

template<typename T>
struct djinni::reference;

This struct implements the basic weak_ptr contract (reset(),lock(),etc) using a holder that is virtual. This allows the implementation of the weak reference mechanics to be customized not only by type, but by instance. If T is a non djinni proxy, its backed by a standard weak_ptr, if instead the instance is a proxy its implemented by holding a weak reference to the platform object (__weak id / WeakReference) and uses the generated toCpp routine to dynamically get/create the proxy when needed.

This results in a string reference from the c++ side keeping the proxied object alive, but a weak reference doesn't. And as soon as the proxied object 'dies' all the weak references properly return an empty shared_ptr when locking. 

Currently I have several working patterns that fully implements working weak_ptr semantics to both native and proxy implementations of a djinni interface

## Option 1 (simpler, less robust, less intrusive)
 djinni-generator -> extended with a new `reference< T >` type that maps to a djinni::reference< T >.
    since the type is parameterized it has access to the generated Marshall contract for any proxied objects. If an platform object is passed to the c++ side as a reference, it generates a reference backed by the weak ref to the platform object.
If the c++ method is called directly from c++ it end up passing a reference backed by a weak_ptr.
 djinni-support-lib -> implementation of the reference template
   
cons: 
* since the translation occurs in the marshaling code, its not possible to convert from a shared_ptr to a reference and maintain the true "weak" reference, as there is no public way to test if an object is a proxy or not.
  benefit

pros:
* minimal changes to the generator, as its all isolated to a new type
* the interface clearly documents the intent of how the object will be used (e.g weakly held vs used/strongly held)
* no hard code links to the platform code (e.g. the same compilation of the c++ code works on all platforms) as the type is "pushed" to the c++ side (just like how an interface is pushed)
    
## Option 2 (more complex, but robust)
 djinni-generator -> extend the generation of the Marshall code to generate the proxies with a marker interface. This provides a way to test if an instance is a proxy or not, and if it is, create a 'safe' weak reference to it.
 djinni-support-lib -> implementation of the reference template, declaration of the djinni::Proxy interface

cons:
* involves changing the generated proxy classes, and having to implement the Proxy interface for each one. (can be managed by a template mostly, but still requires minor changes to the generated class)
* the c++ code has to use the djinni-support-lib directly (currently only the platform implementations need it)

pros:
* since the instances can be "tested" to see if they are proxies, it allows full 'safe' conversion of std::shared_ptr < - > djinni:reference

## Option 3 (more robust, less intrusive - sort of)
 Similar to option 2, but instead of altering the proxies, a factory is exposed. That type is parameterized with the djinni interface providing isProxy / make_reference, implemented by the generated marshaling code
 djinni-generator -> generate an implementation of the ProxyFactory for that type.
 djinni-support-lib -> implementation of the reference template, declaration of the djinni::ProxyFactory interface

cons:
  * the c++ code has a hard dependency on the ProxyFactory, which is generated by the platform marshaling code, and this relies on being linked with a platform. This causes issues if the c++ code is used In a pure c++ fashion as there has to be an implementation of the factory.
  * since there can only be one implementation of the factory, it would not be possible to have a single binary that uses multiple platform implementations (not sure thats current intended to work, but is technically feasible, something like a c++ program that has some objc implementations of things and some java)

NOTE: both of the above could be mitigated using a factory 'registration' mechanism (similar to how the JNI code manages its JniClass instances

pros:
 * reduced / more isolated changes to the generator

**Comment by a4z** [comment]
Can you please help me with that a little bit:

* As a user, what is the problem that I have, with a realistic use case,  for which we need a solution.
* Would it be possible to provide a small code example that is broken, or shows what could be simplified /  improved?

**Comment by eakoli** [comment]
```
callback = interface +o +c {
    onEvent1();
    onEvent2();
}

provider = interface +c {
    static create(): provider;
    setCallback( val : callback );
}
```

// c++ code
```
   class ProviderImpl : public Provider {
       std::shared_ptr<Provider> create() override { 
           return std::make_shared<ProviderImpl>(); 
       }

      void setCallback( const std::shared_ptr& cb ) override {
#if USE_WEAK
          // this will result in the proxy object being destroyed after exiting this method, as there is no string reference to it
          _weak_callback = cb;
#else
          // this will result in a circular reference causing both the implementer of cb and Provider to never be released. 
         _strong_callback = cb;
#endif 
 

      }

      std::weak_ptr<Callback> _weak_callback;
      std::shared_ptr<Callback> _strong_callback; 
   }
```

// objc code
```
@interface Foo : NSObject
@end

@implementation Foo() <Callback>
@property (strong) Provider* provider
@end

@implementation Foo
-(instancetype) init {
    self = [super init];
    if( self ) {
         self.provider = [Provider create];
         [self.provider setCallback: self];
    }
    return self;
}
@end
```

**Comment by a4z** [comment]
Thanks! I will step through this.

Do you think this is totally separated of https://github.com/cross-language-cpp/djinni-generator/pull/116, or could that be related in some way 
Just asking since both topics are about callbacks and I wonder if there is some bigger picture to thing about.

**Comment by a4z** [comment]
If you work on the same topic, please pair up in https://github.com/cross-language-cpp/djinni-generator/pull/116 and share your POV!

Thanks for the report, will take me some time to check that out, but now with the context, very good and detailed description you provide here!

**Comment by eakoli** [comment]
@a4z I did attempt to implement this entirely as an external type, the issue is that currently there is no way to expose a new type where its a wrapper on the c++ side and just the interface on the other. I did contemplate making a new "interface_wrapper" typedef for external, that would essentially be like "optional" (which is really what the reference type I assed equates to). That way yo could define a infinite number of types that "wrap" interfaces on the c++ side w/o adding explicit support in the generator.

**Comment by eakoli** [comment]
@a4z I have a PR that I will be submitting to the generator in relation to this. It's essentially a slightly different take on option 1, but instead of adding a single new type, it adds a class of types, thus the type and how it works can be entirely defined externally to djinni, thus no changes to the support lib. It was inspired by the example in the support line with date. It adds a new typedef "wrapper" that can only be used via @extern <yaml> if defined a type based off of optional, but allows the translator, idlName c++ typename and nullability to be controlled via the extern defintion. This would allow implementing any any c++ type wrapper (optional, weak_ptr, etc) c++ side from the true representation going to /from the bridge.

**Comment by a4z** [comment]
do you have an eye on this PR? 
https://github.com/cross-language-cpp/djinni-generator/pull/113

To me it seems with the ability to define templates types in all languages (Objective-C , Java, C# and C++) , adding various new types is kind of an option via yaml definitions. (Not sure though what that means for Python, guess I need to find out)

**Comment by a4z** [comment]
Closed due to inactivity, please feel free to re-open this PR in case the topic is still actual.
