### ISSUE TITLE
C++/CLI checks are broken

### ISSUE THREAD

**Issue by jothepro** [cross-language-cpp/djinni-support-lib#70]
When creating the PR for updating the generator, the C++/CLI checks failed. 
They seem to be broken for main (djinni-generator v1.2.0) & my PR (djinni-generator v1.3.0):
- https://github.com/cross-language-cpp/djinni-support-lib/actions/runs/1505094405
- https://github.com/cross-language-cpp/djinni-support-lib/actions/runs/1439473067

**Comment by jothepro** [comment]
I've analyzed the problem and came to the following conclusion:

Because of a change in CMake or Visual Studio only the first custom command added by `add_custom_command()`  is executed at build time, all custom commands added afterwards are ignored.
You can see that in the build logs:

Before:
```
Generating Djinni C++ bindings from D:/a/djinni-support-lib/djinni-support-lib/test-suite/djinni/all.djinni
Parsing...
Resolving...
Generating...
Generating Djinni C++/CLI bindings from D:/a/djinni-support-lib/djinni-support-lib/test-suite/djinni/all.djinni
Parsing...
Resolving...
Generating...
Generating Djinni C++ bindings from D:/a/djinni-support-lib/djinni-support-lib/test-suite/djinni/wchar_test.djinni
Parsing...
Resolving...
Generating...
Generating Djinni C++/CLI bindings from D:/a/djinni-support-lib/djinni-support-lib/test-suite/djinni/wchar_test.djinni
Parsing...
Resolving...
Generating...
[Starts compiling]
```
After:
```
Generating Djinni C++ bindings from D:/a/djinni-support-lib/djinni-support-lib/test-suite/djinni/all.djinni
Parsing...
Resolving...
Generating...
[No all.djinni C++/CLI generation, no wchar_test.djinni generation]
[yada yada warnings because files are missing]
[Starts compiling]
```


If I change the order of the `add_custom_command` calls in `Djinni.cmake` by moving [the C++/CLI block](https://github.com/cross-language-cpp/djinni-support-lib/blob/main/test-suite/Djinni.cmake#L405) in line 272, which is in front of the C++ block, I was able to execute the C++/CLI generation command but not the C++ generation command for `all.djinni`.

To sum it up: Only the first custom command of [the first `add_djinni_target` call](https://github.com/cross-language-cpp/djinni-support-lib/blob/main/test-suite/CMakeLists.txt#L14) is executed, all others are ignored. That's why we are missing a lot of files for compiling the tests.

I propose 3 different approaches to solve the problem:
- Track down why the custom commands are broken and fix them. With my current knowledge I cannot say if this is intended behavior, if sth is broken and we can expect a fix in CMake/Visual Studio or if we are just using `add_custom_command()` wrong.
- Re-structure `Djinni.cmake` to generate the gluecode at configuration instead of build time. This would also reduce the complexity of the whole build configuration IMO.

Both things will take a while I guess... 🤷 
Which solution do you prefer, @a4z @freitass ? Any other suggestions?

**Comment by a4z** [comment]
Great catch @jothepro !! 

That this seems happens only on Windows makes it difficult to track it down for some of us.
Do you know the cmake version, because if it's cmake, it should be able to reproduce that problem on OSX/Linux with the same version.
Also interesting if this is something to report to CMake bug list .... in this case we should not do anything atm... except maybe adding a custom cmake to pass the CI

**Comment by jothepro** [comment]
It's definitely not CMake alone, which is causing the problem. It could be the CMake Visual Studio generator though. I have to admit that these are just assumptions.
All github runners are currently running on the latest CMake version 3.22, but the problem only occurs on the Windows build, so you will not be able to reproduce this outside of Windows.

Yup, downgrading CMake and/or Visual Studio could be a temporary solution.

**Comment by a4z** [comment]
I could verify locally that the breaking part is `cmake 3.22.0`

Using `cmake 3.21.4` the code generation via `add_custom_command` works 

but our Test need to target the latest dot net for VS 17/2022, but this is a different topic.
so only VS 16/2019, as we have it in the CI,  is currently a valid option 

Now the question is, is that a cmake problem that was introduced with 3.22.0
Is there some breaking change we should know about
Shall we try to find a workaround, if it worked so far ...?

**Comment by a4z** [comment]
Informed kitware about that bug:
https://gitlab.kitware.com/cmake/cmake/-/issues/22964
let's see if we get some help, 

until this question is solved, I would suggest to go back to cmake 3.21.4

**Comment by a4z** [comment]
It's now confirmed that this is a regression problem in cmake
see: https://gitlab.kitware.com/cmake/cmake/-/issues/22964#note_1093195

So we need just to wait for the next cmake version and until MS has it in the build machiens, and the problem will go away.

The resulting question for the future is:
Do we want to protect our self from such a scenario in future, and take over control over used cmake version
or not
I see advantages in both ....

**Comment by jothepro** [comment]
Are you suggesting to define the cmake-version in the conanfile? I think that would be the most cross-platform solution to control the cmake version? 🤔

**Comment by a4z** [comment]
using cmake via conan works, if conan is the build tool (conan -> cmake -> build) 
it's also possible to use that: https://pypi.org/project/cmake/ , via pip and a version 

But the more I think, the more I think why not leave it as it is.
It will autorepair with the next cmake release 
And if we would have a fix cmake version, we might get a user report about something failing, and than we do not know what it is.
If things break early for us, we can add a note, or something (that no one will ever see but at least we have something)

**Comment by a4z** [comment]
cmake 3.22.1 is out, lets see when it comes to gh actions , and if it fixes our problem
https://blog.kitware.com/cmake-3-22-1-available-for-download/

**Comment by jothepro** [comment]
FYI the CMake update to 3.22.1 for the Windows runner seem to be on it's way. The related PR for updating the documentation is already approved: https://github.com/actions/virtual-environments/pull/4724
