### ISSUE TITLE
What about the NativeLibLoader?

### ISSUE THREAD

**Issue by jothepro** [cross-language-cpp/djinni-support-lib#8]
In [`java/com/dropbox/djinni/NativeLibLoader.java`](https://github.com/cross-language-cpp/djinni-support-lib/blob/main/java/com/dropbox/djinni/NativeLibLoader.java) a class to help loading native libs is provided. I'm not sure how it is supposed to work because I never had to use it.

As a maintainer I'd like to get an answer to the following questions:

- **How should the loader be distributed?** The best option to me seems to move it to a separate repo & publish it as library on some package registry.
- **When and how should it be used?** Currently there is just a [single paragraph in the docs](https://djinni.xlcpp.dev/djinni-generator/generated-code-usage/#our-jni-approach) about it, but it's in the wrong place and not up-to-date.

Additionally I'd like to adapt the package of the class to match our organization (`com.github.cross-language-cpp`)

**Comment by paulo-coutinho** [comment]
I have it into my project and two main.cpp. One with auto load and other with append mode:

https://github.com/ezored/ezored/tree/master/files/gluecode/support-lib/java/com/dropbox/djinni
and
https://github.com/ezored/ezored/tree/master/files/gluecode/support-lib/djinni/jni

**Comment by freitass** [comment]
I ended up using the `NativeLibLoader.java` for the test-suite in https://github.com/cross-language-cpp/djinni-support-lib/pull/17. I'm not sure how useful it is otherwise except as a reference for new developers looking into adopting Djinni on their project.

**Comment by a4z** [comment]
I think we can close this issue.
The NativeLibLoader.java is used for the test suite, and therefore it has it's right to be in the project, but it's internal only.
