### ISSUE TITLE
Provide CMake cross compile options for iOS / Android  

### ISSUE THREAD

**Issue by a4z** [cross-language-cpp/djinni-support-lib#9]
Since CMake 3.14 there are cross compile options for iOS and Android available
see:
https://cmake.org/cmake/help/v3.14/manual/cmake-toolchains.7.html#cross-compiling-for-android-with-the-ndk

Add using this as an option to the build. 
This shall be optional because some users might prefer to pass own toolchaine files to the build

**Comment by epicstar** [comment]
Just FYI... for Android, I'm consuming this repo as a submodule inside my Android Studio project, then including the CMakeLists.txt in this repo... Something like this:

```cmake
...
if (BUILD_WITH_JNI)
  set(DJINNI_WITH_JNI on CACHE BOOL "enable or disable djinni JNI" FORCE)
endif()

if (DJINNI_WITH_JNI OR DJINNI_WITH_OBJC)
  message("loading djinni")
  add_subdirectory(${CMAKE_CURRENT_LIST_DIR}/external/djinni-support-lib)
else()
  message("not loading djinni")
endif()
```

The Android Gradle Plugin already plugs in the Android toolchain bundled with the Android SDK + NDK, so everything works as expected. I guess all that's left on the Android side is to document a recommended way to consuming the repository.

**Comment by a4z** [comment]
Yes, if you include this project as a subproject, and use it via Android Studio, gradle does call cmake with the Android CMake Toolchain file and everything is fine.

I have builds for this lib  with the ndk and ios-cmake toolchain file.  Both work. I will soon also provide them as conan packages.
I think this is a good way, let the user to provide the right settings since they can contain individual tweaks and work with those, but I still would like to research additional options, once my time allows that.

**Comment by a4z** [comment]
I close this since I think it is up to the user to provide a toolchain file, and the support lib shall be able the compile with a toolchain file provided. This is currently the case.
